---

- hosts: revspace
  become: yes
  roles:
    - { role: "common", tags: [ "common" ] }
    - { role: "dehydrated", tags: [ "dehydrated" ] }
    - { role: "unattended-upgrade", tags: [ "unattended-upgrade" ] }

- hosts: memberservers
  become: yes
  roles:
    - { role: "ldapclient", tags: [ "ldapclient" ] }

- hosts: ldap.space.revspace.nl
  become: yes
  roles:
    - { role: "ldapserver", tags: [ "ldapserver" ] }

- hosts: icinga.space.revspace.nl
  become: yes
  roles:
    - { role: "dehydrated", tags: [ "dehydrated" ] }
    - { role: "icinga", tags: [ "icinga" ] }

