# Installation instructions before ansible will work for openwrt/gl-inet devices
#
# Allow root-logins with certificate
#

- hosts: glinet
  gather_facts: no
  vars:
  sudo: no
  user: root 
  tasks:

  - name: Update opkg indexes
    raw: /bin/opkg update

  - name: Install sftp server
    raw: /bin/opkg install openssh-sftp-server

  - name: Install python
    raw: /bin/opkg install python python-json

  - name: Update opkg indexes
    command: /bin/opkg update

  - name: Install required base packages
    opkg: name={{item}} state=installed
    with_items:
      - shadow-groupadd
      - shadow-useradd
      - shadow-groupmod
      - shadow-usermod

  - name: Create 'pi' group
    group: gid=1000 name=pi state=present system=no

  - name: Create 'pi' user
    user: comment='Doorduino User' group=pi createhome=yes name=pi password="{{passwordpi}}" state=present update_password=always

  - name: Install required perl packages for doorduino code
    opkg: name={{item}} state=installed
    with_items:
      - perl
      - screen
      - strace
      - sudo
      - perlbase-essential
      - perlbase-autoloader
      - perlbase-config
      - perlbase-digest
      - perlbase-dynaloader
      - perlbase-errno
      - perlbase-fcntl
      - perlbase-file
      - perlbase-integer
      - perlbase-io
      - perlbase-posix
      - perlbase-selectsaver
      - perlbase-socket
      - perlbase-symbol
      - perlbase-sys
      - perlbase-tie
      - perlbase-xsloader
      - coreutils-stty
      - curl
      - kmod-usb-core
      - kmod-usb2
      - kmod-usb-serial
      - kmod-usb-serial-ftdi
