# LDAP Client role for Revspace LDAP
# Tested on: Debian Stable

---

  - name: Install LDAP client software
    apt: name={{item}} state=installed
    when: ansible_os_family == 'Debian'
    with_items:
      - libpam-ldapd
    tags:
      - ldapclient
      - apt

  - name: Enable pam_mkhomedir module
    lineinfile: dest=/etc/pam.d/common-account line="session    required   pam_mkhomedir.so skel=/etc/skel/ umask=0022" regexp="pam_mkhomedir.so" insertafter=EOF
    tags:
      - ldapclient
      - mkhomedir

  - name: Create login.group.allowed file
    lineinfile: dest=/etc/login.group.allowed line="board" regexp="^board$" owner=root group=root mode=0755 create=yes
    with_items:
      - "{{login_groups | default('board') }}"
    tags:
      - ldapclient
      - logingroups

  - name: Limit access to listed groups
    lineinfile: dest=/etc/pam.d/common-auth line="auth required pam_listfile.so onerr=fail item=group sense=allow file=/etc/login.group.allowed" owner=root group=root mode=0644 regexp="pam_listfile,*login\.group\.allowed" insertbefore=EOF
    tags:
      - ldapclient
      - logingroups

  - name: Disable nscd service
    service: name=nscd state=stopped enabled=false
    tags:
      - ldapclient
      - nscd

  - name: Restart nslcd service
    service: name=nslcd state=restarted enabled=true
    tags:
      - ldapclient
      - nslcd

